version: '3'


services:
  zoo1:
    image: zookeeper
    ports:
      - 127.0.0.1:2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./data/zoo1/data:/data:delegated
      - ./data/zoo1/datalog:/datalog:delegated
  zoo2:
    image: zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./data/zoo2/data:/data:delegated
      - ./data/zoo2/datalog:/datalog:delegated

  zoo3:
    image: zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./data/zoo3/data:/data:delegated
      - ./data/zoo3/datalog:/datalog:delegated

  kafka1:
    image: imankulov/kafka
    build: kafka
    environment:
      KAFKA_BROKER_ID: "1"
    volumes:
      - ./data/kafka1/kafka-logs:/kafka-logs:delegated

  kafka2:
    image: imankulov/kafka
    build: kafka
    environment:
      KAFKA_BROKER_ID: "2"
    volumes:
      - ./data/kafka2/kafka-logs:/kafka-logs:delegated

  connect:
    image: imankulov/kafka-connect
    build: connect
    ports:
      - 127.0.0.1:8083:8083

  client:
    image: imankulov/kafka-client
    build: client
    volumes:
      - ./playground:/app/playground
      - ./client-home:/home/client
    ports:
      - 127.0.0.1:6066:6066
